FROM {{jdk.image}}
VOLUME /tmp
EXPOSE {{application.port}}
EXPOSE 5005
ADD build/libs/{{application.name}}.jar app.jar
ENV JAVA_OPTS=""
ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar
